- name: Add project
  awx.awx.project:
    name: "{{ project_name }}"
    description: "{{ project_description }}"
    organization: "Default"
    state: present
    scm_type: git
    scm_url: "{{ scm_url }}"
    scm_branch: "{{ scm_branch }}"
    credential: "GitHub"
    scm_update_on_launch: True
    scm_update_cache_timeout: 60
    validate_certs: no
    controller_oauthtoken: "{{ awx_admin_token }}"