# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ol8-gnome.box"
  config.vm.network "private_network", ip: "192.168.56.15"
  config.vm.hostname = "ol8-gnome"

  # Uncomment the below line to install and configure VNC
  # config.vm.provision "shell", path: "scripts/install-vnc.sh"
end
