Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.name = "podman-machine"
  end
  config.vm.box = "oraclelinux/8"
  config.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/8.json"
  config.vm.hostname = "podman"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end
  config.vm.network "private_network", ip: "192.168.56.100"

  # Mount host system under /mnt (similar to what is done in WSL)
  config.vm.synced_folder "/", "/mnt", automount: true

  # Copy ed25519 public key into authorized keys (because using the RSA key causes connection issues)
  # Set SELINUX to permissive and install Podman
  ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_ed25519.pub").first.strip
  config.vm.provision "shell", inline: <<-SHELL
    echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    sed -i s/^SELINUX=.*$/SELINUX=permissive/ /etc/selinux/config
    setenforce 0
    dnf module install -y container-tools:ol8
    loginctl enable-linger vagrant
  SHELL

  # Enable the Podman socket
  config.vm.provision "shell", inline: "systemctl --user enable --now podman.socket", privileged: false

end