- name: Create job for each location
  awx.awx.job_template:
    name: "{{ item.name }}"
    job_type: "run"
    organization: "Default"
    inventory: "{{ item.name }}"
    project: "{{ project_name }}"
    playbook: "{{ playbook }}"
    credentials:
      - "Ansible Vault"
    job_tags: "debug"
    state: "present"
    validate_certs: no
    controller_oauthtoken: "{{ awx_admin_token }}"
  loop: "{{ vars.inventory }}"