# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
require 'ipaddr'

variables = YAML.load_file(File.join(File.dirname(__FILE__), 'variables.yaml'))
ip = IPAddr.new(variables['hostname'])
client_ip = ip.native

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--groups", "/OLM"]
  end

  config.vm.define "olm" do |olm|
    olm.vm.provider "virtualbox" do |v|
      v.name = "Oracle Linux Manager"
    end
    olm.vm.box = "oraclelinux/7"
    olm.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/7.json"
    olm.vm.network "private_network", ip: ip.to_string
    olm.vm.hostname = "olm"

    olm.vm.provision "file", source: "files/answer-file.txt", destination: "/tmp/answer-file.txt"
    olm.vm.provision "shell", path: "scripts/provision.sh"
    olm.vm.provision "shell", path: "scripts/first-user.sh"

    # Configure custom API
    if(File.file?("olm-api/fastapi.sh"))
      olm.vm.provision "file", source: "olm-api", destination: "/home/vagrant/olm-api"
      olm.vm.provision "shell", inline: "envsubst '$OLM_HOSTNAME' </home/vagrant/olm-api/src/api.py.template >/home/vagrant/olm-api/src/api.py", env: { "OLM_HOSTNAME"=>variables['hostname'] }
      olm.vm.provision "shell", path: "olm-api/fastapi.sh", env: { "OLM_HOSTNAME"=>variables['hostname'] }
    end

    olm.vm.provision "shell", path: "scripts/olm-config.sh", env: { "OLM_HOSTNAME"=>variables['hostname'] }

    # Configure ULN
    if(File.file?("scripts/secret.sh")) 
      olm.vm.provision "shell", path: "scripts/secret.sh"
    end

    olm.vm.provision "shell", inline: "echo Access Oracle Linux Manager at https://${OLM_HOSTNAME}", env: { "OLM_HOSTNAME"=>variables['hostname'] }
  end

  config.vm.define "client7" do |client7|
    client7.vm.provider "virtualbox" do |v|
      v.name = "OL7 Client"
      v.memory = 1024
      v.cpus = 1
    end
    client7.vm.box = "oraclelinux/7"
    client7.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/7.json"
    client_ip = client_ip.succ; client7.vm.network "private_network", ip: client_ip.to_string
    client7.vm.hostname = "ol7"

    client7.vm.provision "shell", path: "scripts/register7.sh", env: {
      "OLM_HOSTNAME"=>variables['hostname']
    }
  end

  config.vm.define "client8" do |client8|
    client8.vm.provider "virtualbox" do |v|
      v.name = "OL8 Client"
      v.memory = 1024
      v.cpus = 1
    end
    client8.vm.box = "oraclelinux/8"
    client8.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/8.json"
    client_ip = client_ip.succ; client8.vm.network "private_network", ip: client_ip.to_string
    client8.vm.hostname = "ol8"

    client8.vm.provision "shell", path: "scripts/register8.sh", env: {
      "OLM_HOSTNAME"=>variables['hostname']
    }
  end
end