Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--groups", "/OLM"]
  end

  config.vm.define "server" do |server|
    server.vm.provider "virtualbox" do |v|
      v.name = "Oracle Linux Manager"
    end
    server.vm.box = "oraclelinux/7"
    server.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/7.json"
    server.vm.network "private_network", ip: "192.168.56.10"
    server.vm.hostname = "olm"

    server.vm.provision "file", source: "answer-file.txt", destination: "/tmp/answer-file.txt"
    server.vm.provision "shell", path: "provision.sh"
    server.vm.provision "shell", path: "first-user.sh"
    server.vm.provision "shell", path: "olm-config.sh"
    if(File.file?("secret.sh")) 
      server.vm.provision "shell", path: "secret.sh"
    end
    server.vm.provision "shell", inline: "echo Access Oracle Linux Manager at https://192.168.56.10"
  end

  config.vm.define "client7" do |client7|
    client7.vm.provider "virtualbox" do |v|
      v.name = "OL7 Client"
      v.memory = 1024
      v.cpus = 1
    end
    client7.vm.box = "oraclelinux/7"
    client7.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/7.json"
    client7.vm.network "private_network", ip: "192.168.56.11"
    client7.vm.hostname = "ol7"

    client7.vm.provision "shell", path: "register7.sh"
  end

  config.vm.define "client8" do |client8|
    client8.vm.provider "virtualbox" do |v|
      v.name = "OL8 Client"
      v.memory = 1024
      v.cpus = 1
    end
    client8.vm.box = "oraclelinux/8"
    client8.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/8.json"
    client8.vm.network "private_network", ip: "192.168.56.12"
    client8.vm.hostname = "ol8"

    client8.vm.provision "shell", path: "register8.sh"
  end
end