require 'yaml'

variables = YAML.load_file(File.join(File.dirname(__FILE__), 'variables.yaml'))

Vagrant.configure("2") do |config|
    config.vm.define "ksplice" do |ksplice|
      ksplice.vm.provider "virtualbox" do |v|
        v.name = "Ksplice Demo"
      end
      ksplice.vm.box = "ol7-ksplice-dirtycow.box"
      ksplice.vm.network "private_network", ip: "192.168.56.10"
      ksplice.vm.hostname = "ksplice-demo"

      ksplice.vm.provision 'shell', path: "scripts/provision.sh", env: {
        "USERNAME"=>variables['uln']['username'],
        "PASSWORD"=>variables['uln']['password'],
        "CSI"=>variables['uln']['csi']
      }

    end
  end