# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
variables = YAML.load_file(File.join(File.dirname(__FILE__), 'variables.yaml'))

Vagrant.configure("2") do |config|
  config.vm.box = "oraclelinux/8"
  config.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/8.json"

  config.vm.provider "virtualbox" do |v|
    v.name = "WireGuard VPN"
  end

  config.vm.hostname = "wireguard-vpn"

  if variables['network'] == "nat"
    config.vm.network "forwarded_port", guest: variables['listen_port'], host: variables['listen_port'], protocol: "udp"
  end

  config.vm.provision 'shell', path: "scripts/provision.sh", env: {
    "DUCKDNS"=>variables['duckdns']['enabled'],
    "TOKEN"=>variables['duckdns']['token'],
    "SUBDOMAIN"=>variables['duckdns']['subdomain'],
    "FQDN"=>variables['duckdns']['fqdn'],
    "LISTEN_PORT"=>variables['listen_port']
  }
end