---
- fail: msg="use non-root account for this playbook"
  when: ansible_user_id == "root"

- name: check if sudo is working
  shell: whoami
  register: whoami
  become: true

- debug: msg="sudo -> {{whoami.stdout}} = OK"


- block:

  - name: create temp dir
    file:
      path: "{{directory}}"
      state: directory

  - name: copy exploit source file
    copy:
      src: dirtyc0w.c
      dest: "{{directory}}/dirtyc0w.c"

  - name: compile
    shell: "gcc -pthread dirtyc0w.c -o dirtyc0w"
    args:
      chdir: "{{directory}}"

  - name: create file with root account
    copy:
      src: foo
      dest: "{{directory}}/foo"
      owner: root
      group: root
      mode: '0404'
    become: true

  - name: run exploit
    shell: "./dirtyc0w foo {{exploit_string}}"
    args:
      chdir: "{{directory}}"
    ignore_errors: yes

  - name: check result
    shell: "grep {{exploit_string}} foo"
    args:
      chdir: "{{directory}}"
    register: result
    ignore_errors: yes

  - name: result
    fail: msg="vulnerable"
    when: result.rc == 0


  - name: result
    debug: msg="NOT vulnerable"
    when: result.rc != 0

#  rescue:

  always:

  - name: delete temp dir
    file:
      path: "{{directory}}"
      state: absent


