# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
require 'ipaddr'

variables = YAML.load_file(File.join(File.dirname(__FILE__), 'variables.yaml'))
ip = IPAddr.new(variables['hostname'])
client_ip = ip.native

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--groups", "/OLAM"]
  end

  config.vm.define "olam" do |olam|
    olam.vm.provider "virtualbox" do |v|
      v.name = "Oracle Linux Automation Manager"
    end
    olam.vm.box = "oraclelinux/8"
    olam.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/8.json"
    olam.vm.network "private_network", ip: ip.to_string
    olam.vm.hostname = "olam"

    olam.vm.provision 'shell', path: "scripts/provision.sh", env: {
      "HOSTNAME"=>variables['hostname'],
      "EMAIL"=>variables['email'],
      "PASSWORD"=>variables['password'],
      "SAMPLE_DEPLOYMENT"=>variables['sample_deployment']
    }

    olam.vm.provision "shell", inline: "echo Access Oracle Linux Automation Manager at ${HOSTNAME}", env: { "HOSTNAME"=>variables['hostname'] }
  end

  # Deploy sample hosts
  if(variables['sample_deployment'] == true)

    config.vm.define "atlanta_1" do |atlanta_1|
      atlanta_1.vm.provider "virtualbox" do |v|
        v.name = "Atlanta 1"
      end
      atlanta_1.vm.box = "oraclelinux/8"
      atlanta_1.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/8.json"
      client_ip = client_ip.succ; atlanta_1.vm.network "private_network", ip: client_ip.to_string
      atlanta_1.vm.hostname = "atlanta1"
      atlanta_1.vm.provision "shell", inline: "echo 'vagrant:vagrant' | chpasswd; sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config; systemctl restart sshd.service"
    end

    config.vm.define "atlanta_2" do |atlanta_2|
      atlanta_2.vm.provider "virtualbox" do |v|
        v.name = "Atlanta 2"
      end
      atlanta_2.vm.box = "oraclelinux/8"
      atlanta_2.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/8.json"
      client_ip = client_ip.succ; atlanta_2.vm.network "private_network", ip: client_ip.to_string
      atlanta_2.vm.hostname = "atlanta2"
      atlanta_2.vm.provision "shell", inline: "echo 'vagrant:vagrant' | chpasswd; sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config; systemctl restart sshd.service"
    end

    config.vm.define "raleigh_1" do |raleigh_1|
      raleigh_1.vm.provider "virtualbox" do |v|
        v.name = "Raleigh 1"
      end
      raleigh_1.vm.box = "oraclelinux/8"
      raleigh_1.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/8.json"
      client_ip = client_ip.succ; raleigh_1.vm.network "private_network", ip: client_ip.to_string
      raleigh_1.vm.hostname = "raleigh1"
      raleigh_1.vm.provision "shell", inline: "echo 'vagrant:vagrant' | chpasswd; sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config; systemctl restart sshd.service"
    end

    config.vm.define "raleigh_2" do |raleigh_2|
      raleigh_2.vm.provider "virtualbox" do |v|
        v.name = "Raleigh 2"
      end
      raleigh_2.vm.box = "oraclelinux/8"
      raleigh_2.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/8.json"
      client_ip = client_ip.succ; raleigh_2.vm.network "private_network", ip: client_ip.to_string
      raleigh_2.vm.hostname = "raleigh2"
      raleigh_2.vm.provision "shell", inline: "echo 'vagrant:vagrant' | chpasswd; sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config; systemctl restart sshd.service"
    end

  end

end