- name: Create a valid GitHub SCM credential
  awx.awx.credential:
    name: GitHub
    organization: Default
    state: present
    credential_type: Source Control
    inputs:
      username: "{{ github_username }}"
      password: "{{ github_pat }}"
    validate_certs: no
    controller_oauthtoken: "{{ awx_admin_token }}"

- name: Create a credential for Ansible Vault
  awx.awx.credential:
    name: Ansible Vault
    organization: Default
    state: present
    credential_type: Vault
    inputs:
      vault_password: "{{ vault_password }}"
    validate_certs: no
    controller_oauthtoken: "{{ awx_admin_token }}"